src/objects/Limit_Log__c.object
<CustomObject>
    <fields>
        <fullName>Aggregate_Queries_Limit__c</fullName>
        <description>The limit of Aggregate_Queries that can be performed in this type of context</description>
        <inlineHelpText>The limit of Aggregate_Queries that can be performed in this type of context</inlineHelpText>
        <label>Aggregate Queries Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Aggregate_Queries_Used__c</fullName>
        <description>Aggregate Queries used during this log period</description>
        <inlineHelpText>Aggregate Queries used during this log period</inlineHelpText>
        <label>Aggregate Queries Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Async_Calls_Limit__c</fullName>
        <description>The limit of Async_Calls that can be performed in this type of context</description>
        <inlineHelpText>The limit of Async_Calls that can be performed in this type of context</inlineHelpText>
        <label>Async Calls Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Async_Calls_Used__c</fullName>
        <description>Async Calls used during this log period</description>
        <inlineHelpText>Async Calls used during this log period</inlineHelpText>
        <label>Async Calls Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Batchable__c</fullName>
        <description>Was this logged during a batch context</description>
        <inlineHelpText>Was this logged during a batch context</inlineHelpText>
        <defaultValue>false</defaultValue>
        <label>Batchable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CPU_Time_Limit__c</fullName>
        <description>The limit of CPU_Time that can be performed in this type of context</description>
        <inlineHelpText>The limit of CPU_Time that can be performed in this type of context</inlineHelpText>
        <label>CPU Time Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Callouts_Limit__c</fullName>
        <description>The limit of Callouts that can be performed in this type of context</description>
        <inlineHelpText>The limit of Callouts that can be performed in this type of context</inlineHelpText>
        <label>Callouts Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Callouts_Used__c</fullName>
        <description>Callouts used during this log period</description>
        <inlineHelpText>Callouts used during this log period</inlineHelpText>
        <label>Callouts Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cumulative_Aggregate_Queries_Used__c</fullName>
        <description>Cumulative Aggregate Queries used up until this point in the execution context.</description>
        <inlineHelpText>Cumulative Aggregate Queries used up until this point in the execution context</inlineHelpText>
        <label>Cumulative Aggregate Queries Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cumulative_Async_Calls_Used__c</fullName>
        <description>Cumulative Async Calls used up until this point in the execution context.</description>
        <inlineHelpText>Cumulative Async Calls used up until this point in the execution context</inlineHelpText>
        <label>Cumulative Async Calls Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cumulative_Callouts_Used__c</fullName>
        <description>Cumulative Callouts used up until this point in the execution context.</description>
        <inlineHelpText>Cumulative Callouts used up until this point in the execution context</inlineHelpText>
        <label>Cumulative Callouts Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DML_Rows_Limit__c</fullName>
        <description>The limit of DML Rows that can be performed in this type of context</description>
        <inlineHelpText>The limit of DML Rows that can be performed in this type of context</inlineHelpText>
        <label>DML Rows Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DML_Statements_Limit__c</fullName>
        <description>The limit of DML Statements that can be performed in this type of context</description>
        <inlineHelpText>The limit of DML Statements that can be performed in this type of context</inlineHelpText>
        <label>DML Statements Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Invocations_Limit__c</fullName>
        <description>The limit of Email Invocations that can be performed in this type of context</description>
        <inlineHelpText>The limit of Email Invocations that can be performed in this type of context</inlineHelpText>
        <label>Email Invocations Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Future_Calls_Limit__c</fullName>
        <description>The limit of Future Calls that can be performed in this type of context</description>
        <inlineHelpText>The limit of Future Calls that can be performed in this type of context</inlineHelpText>
        <label>Future Calls Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Future__c</fullName>
        <description>Was this logged during a future context</description>
        <inlineHelpText>Was this logged during a future context</inlineHelpText>
        <defaultValue>false</defaultValue>
        <label>Future</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Heap_Size_Limit__c</fullName>
        <description>The limit of Heap Size that can be performed in this type of context</description>
        <inlineHelpText>The limit of Heap Size that can be performed in this type of context</inlineHelpText>
        <label>Heap Size Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Log_Start_Order__c</fullName>
        <label>Log Start Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Log_Stop_Order__c</fullName>
        <label>Log Stop Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mobile_Push_Apex_Calls_Limit__c</fullName>
        <description>The limit of Mobile Push Apex Calls that can be performed in this type of context</description>
        <inlineHelpText>The limit of Mobile Push Apex Calls that can be performed in this type of context</inlineHelpText>
        <label>Mobile Push Apex Calls Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Queries_Limit__c</fullName>
        <description>The limit of Queries that can be performed in this type of context</description>
        <inlineHelpText>The limit of Queries that can be performed in this type of context</inlineHelpText>
        <label>Queries Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Queries_Used__c</fullName>
        <description>Queries used during this log period</description>
        <inlineHelpText>Queries used during this log period</inlineHelpText>
        <label>Queries Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Query_Locator_Rows_Limit__c</fullName>
        <description>The limit of Query Locator Rows that can be performed in this type of context</description>
        <inlineHelpText>The limit of Query Locator Rows that can be performed in this type of context</inlineHelpText>
        <label>Query Locator Rows Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Query_Rows_Limit__c</fullName>
        <description>The limit of Query Rows that can be performed in this type of context</description>
        <inlineHelpText>The limit of Query Rows that can be performed in this type of context</inlineHelpText>
        <label>Query Rows Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Queueable_Jobs_Limit__c</fullName>
        <description>The limit of Queueable Jobs that can be performed in this type of context</description>
        <inlineHelpText>The limit of Queueable Jobs that can be performed in this type of context</inlineHelpText>
        <label>Queueable Jobs Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Queueable__c</fullName>
        <description>Was this logged during a Queueable context</description>
        <inlineHelpText>Was this logged during a Queueable context</inlineHelpText>
        <defaultValue>false</defaultValue>
        <label>Queueable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Records_Processed__c</fullName>
        <label>Records Processed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scheduled__c</fullName>
        <description>Was this logged during a scheduled context</description>
        <inlineHelpText>Was this logged during a scheduled context</inlineHelpText>
        <defaultValue>false</defaultValue>
        <label>Scheduled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sosl_Queries_Limit__c</fullName>
        <description>The limit of Sosl_Queries that can be performed in this type of context</description>
        <inlineHelpText>The limit of Sosl_Queries that can be performed in this type of context</inlineHelpText>
        <label>Sosl Queries Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction #</label>
        <description>Transaction # for the execution context. Log with same transaction number were created in the same execution context</description>
        <inlineHelpText>Transaction # for the execution context. Log with same transaction number were created in the same execution context</inlineHelpText>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wrapper_Limit_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is populated if there is a parent log associated to this log - e.g. multiple logs in the same execution context</description>
        <inlineHelpText>This is populated if there is a parent log associated to this log - e.g. multiple logs in the same execution context</inlineHelpText>
        <label>Wrapper Limit Log</label>
        <referenceTo>Limit_Log__c</referenceTo>
        <relationshipLabel>Limit Logs</relationshipLabel>
        <relationshipName>Limit_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Limit Log</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Limit Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Limit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Limit_Logger_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Auto_Commit_When_Initial_Is_Stopped__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Auto commit the logs when the initial log is stopped. Without this being set to true, you must call the &quot;commitAll&quot; method in order to commit the logs.</description>
        <inlineHelpText>Auto commit the logs when the initial log is stopped. Without this being set to true, you must call the &quot;commitAll&quot; method in order to commit the logs.</inlineHelpText>
        <label>Auto Commit When Initial Is Stopped</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Commit_Logs_To_Database__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if the Limit Logs are committed to the Limit Log object. Can also be programmatically set via LimitLogger.commitLogs = true</description>
        <inlineHelpText>Determines if the Limit Logs are committed to the Limit Log object. Can also be programmatically set via LimitLogger.commitLogs = true</inlineHelpText>
        <label>Commit Logs To Database</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Debug_Limits__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines if the Limit Logs are printed in the debug logs. Can also be programmatically set via LimitLogger.debugLogs = true</description>
        <inlineHelpText>Determines if the Limit Logs are printed in the debug logs. Can also be programmatically set via LimitLogger.debugLogs = true</inlineHelpText>
        <label>Debug Limits</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Set_Wrapper_Relationships_Between_Logs__c</fullName>
        <defaultValue>true</defaultValue>
        <description>The wrapper relationship sets parent child relationships between the log limits. This will consume an extra DML statement and the corresponding number of DML rows.</description>
        <inlineHelpText>The wrapper relationship sets parent child relationships between the log limits. This will consume an extra DML statement and the corresponding number of DML rows.</inlineHelpText>
        <label>Set Wrapper Relationships Between Logs</label>
        <type>Checkbox</type>
    </fields>
    <label>Limit Logger Settings</label>
</CustomObject>

src/classes/LimitLogger.cls
/**
 * Copyright (c) 2018, Tim Barsotti
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 *   are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 *		this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *		this list of conditions and the following disclaimer in the documentation
 *		and/or other materials provided with the distribution.
 * - Neither the name of the Tim Barsotti, inc nor the names of its contributors
 *		may be used to endorse or promote products derived from this software without
 *		specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES;LOSS OF USE, DATA, OR PROFITS;OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**/
public class LimitLogger {
	/* Constructors */
	/**
	* Constructs a new LimitLogger
	*
	* @param sObjectList A list of objects - the size gets logged in the Limit_Log__c object
	* @param eventName the friendly name for the log - saved in the Limit_Log__c.Event_Name__c
	*/
	public LimitLogger(List<sObject> sObjectList, String eventName) {
		if(limitLoggerEnabled) {
			this(eventName);
			this.sObjectList = sObjectList;
		}
	}
	/**
	* Constructs a new LimitLogger
	*
	* @param eventName the friendly name for the log - saved in the Limit_Log__c.Event_Name__c
	*/

	public LimitLogger(String eventName) {
		if(limitLoggerEnabled) {
			logStartOrder++;
			this.eventName = eventName;
			initializeLimitLogRecord();
			initialLog = this;
			start();
		}
	}

	public LimitLogger() {
		if(limitLoggerEnabled) {
			this(String.valueOf(transactionNumber));
			initializeLimitLogRecord();
		}
	}

	/* inner classes */
	public class LimitLoggerException extends Exception {}
	
	//if the Debug_Limits__c is true, then the logs are printed in the debug logs
	//custom setter allows programmatic overrides
	public static Boolean debugLogs { get {
		if(debugLogs == null) {
			debugLogs = limitLoggerSettings.Debug_Limits__c;
		}
		return debugLogs;
	} set;}

	//if the Commit_Logs_To_Database__c is true, then the logs are saved to the database when the initially constructed limit log is stopped
	//custom setter allows programmatic overrides
	public static Boolean commitLogs { get {
		if(commitLogs == null) {
			commitLogs = limitLoggerSettings.Commit_Logs_To_Database__c;
		}
		return commitLogs;
	} set;}

	/* Attributes */ 
	//if log has stopped already, then don't allow stopping again
	private Boolean stopped {
		get { 
			if(stopped == null) {
				return false;
			} 
			return stopped;
		}
		set { 
			if(stopped != null && stopped) {
				throw new LimitLoggerException(Label.LIMIT_LOG_MAX_ONCE_STOP_EXCEPTION);
			} else if (value) {
				logStopOrder++;
				this.stopped = value;
				this.record.Log_Stop_Order__c = logStopOrder;
			}
		}
	}

	//if this is being processed with a list of sObjects, then the size of the list will be logged to Limit_Log__c.Records_Processed__c
	private List<sObject> sObjectList;

	//the friendly name for the event that this was generated from
	private String eventName;

	//the limit log that is being worked with
	@TestVisible private Limit_Log__c record {get; set;}

	//the initial / cumulativenumber of aggregate queries that have been processed with any SOQL query statement.
	@TestVisible private Integer initialAggregateQueries = 0;
	@TestVisible private Integer cumulativeAggregateQueries {
		get { 
			return LIMITS.getAggregateQueries();
		}
	}
	//Reserved for future use.
	@TestVisible private Integer initialAsyncCalls = 0;
	@TestVisible private Integer cumulativeAsyncCalls {
		get {
			return LIMITS.getAsyncCalls();
		}
	}
	//the initial / cumulative number of Web service statements that have been processed.
	@TestVisible private Integer initialCallouts = 0;
	@TestVisible private Integer cumulativeCallouts {
		get {
			return LIMITS.getCallouts();
		}
	}
	//the initial / cumulative CPU time in milliseconds accumulated on the Salesforce servers in the current transaction.
	@TestVisible private Integer initialCpuTime = 0;
	@TestVisible private Integer cumulativeCpuTime {
		get {
			return LIMITS.getCpuTime();
		}
	}
	//the initial / cumulative number of records that have been processed with any statement that counts against DML limits, such as DML statements, the Database.emptyRecycleBin method, and other methods.
	@TestVisible private Integer initialDMLRows = 0;
	@TestVisible private Integer cumulativeDMLRows {
		get {
			return LIMITS.getDMLRows();
		}
	}
	//the initial / cumulative number of DML statements such as insert, update or the database.EmptyRecycleBin method that have been called.
	@TestVisible private Integer initialDMLStatements = 0;
	@TestVisible private Integer cumulativeDMLStatements {
		get {
			return LIMITS.getDMLStatements();
		}
	}
	//the initial / cumulative number of email invocations such as sendEmail that have been called.
	@TestVisible private Integer initialEmailInvocations = 0;
	@TestVisible private Integer cumulativeEmailInvocations {
		get {
			return LIMITS.getEmailInvocations();
		}
	}
	//the initial / cumulative number of methods with the future annotation that have been executed not necessarily completed.
	@TestVisible private Integer initialFutureCalls = 0;
	@TestVisible private Integer cumulativeFutureCalls {
		get {
			return LIMITS.getFutureCalls();
		}
	}
	//the initial / cumulative approximate amount of memory in bytes that has been used for the heap.
	@TestVisible private Integer initialHeapSize = 0;
	@TestVisible private Integer cumulativeHeapSize {
		get {
			return LIMITS.getHeapSize();
		}
	}
	//the initial / cumulative number of Apex calls that have been used by mobile push notifications during the current metering interval.
	@TestVisible private Integer initialMobilePushApexCalls = 0;
	@TestVisible private Integer cumulativeMobilePushApexCalls {
		get {
			return LIMITS.getMobilePushApexCalls();
		}
	}
	//the cumulative number of SOQL queries that have been issued.
	@TestVisible private Integer initialQueries = 0;
	@TestVisible private Integer cumulativeQueries {
		get {
			return LIMITS.getQueries();
		}
	}
	//the initial / cumulative number of records that have been returned by the Database.getQueryLocator method.
	@TestVisible private Integer initialQueryLocatorRows = 0;
	@TestVisible private Integer cumulativeQueryLocatorRows {
		get {
			return LIMITS.getQueryLocatorRows();
		}
	}
	//the initial / cumulative number of records that have been returned by issuing SOQL queries.
	@TestVisible private Integer initialQueryRows = 0;
	@TestVisible private Integer cumulativeQueryRows {
		get {
			return LIMITS.getQueryRows();
		}
	}
	//the initial / cumulative number of queueable jobs that have been added to the queue per transaction. A queueable job corresponds to a class that implements the Queueable interface.
	@TestVisible private Integer initialQueueableJobs = 0;
	@TestVisible private Integer cumulativeQueueableJobs {
		get {
			return LIMITS.getQueueableJobs();
		}
	}
	//the initial / cumulative number of SOSL queries that have been issued.
	@TestVisible private Integer initialSoslQueries = 0;
	@TestVisible private Integer cumulativeSoslQueries {
		get {
			return LIMITS.getSoslQueries();
		}
	}
	private Boolean triggerIsExecuting {get; set;}
	private Integer triggerSize {get; set;}
	private Set<String> triggerContext {get; set;}
	private Long startTime;
	private Integer endTime;

	/* Statics */
	//running list of Limit_Logs__c to commit later
	private static List<Limit_Log__c> uncommittedRecords = new List<Limit_Log__c>();
	private static List<Limit_Log__c> allWorkingRecords = new List<Limit_Log__c>();

	// static variable used to keep track of whether or not the initial log is the one being stopped or not
	private static LimitLogger initialLog {get; set{
		if(value == null) {
			initialLog = null;
		} else {
			if(initialLog == null) {
				initialLog = value;
			}
		}
	}}

	/** Custom setting derives if the limit logger is enabled. 
	 * if neither checkbox is enabled, nothing happens. 
	 * if the Debug_Limits__c is true, then the logs are printed in the debug logs
	 * if the Commit_Logs_To_Database__c is true, then the logs are saved to the database when the initially constructed limit log is stopped
	 */
	private static Limit_Logger_Settings__c limitLoggerSettings = Limit_Logger_Settings__c.getInstance();
	
	private static Integer limitAggregateQueries = LIMITS.getLimitAggregateQueries();
	private static Integer limitAsyncCalls = LIMITS.getLimitAsyncCalls();
	private static Integer limitCallouts = LIMITS.getLimitCallouts();
	private static Integer limitCpuTime = LIMITS.getLimitCpuTime();
	private static Integer limitDMLRows = LIMITS.getLimitDMLRows();
	private static Integer limitDMLStatements = LIMITS.getLimitDMLStatements();
	private static Integer limitEmailInvocations = LIMITS.getLimitEmailInvocations();
	private static Integer limitFutureCalls = LIMITS.getLimitFutureCalls();
	private static Integer limitHeapSize = LIMITS.getLimitHeapSize();
	private static Integer limitMobilePushApexCalls = LIMITS.getLimitMobilePushApexCalls();
	private static Integer limitQueries = LIMITS.getLimitQueries();
	private static Integer limitQueryLocatorRows = LIMITS.getLimitQueryLocatorRows();
	private static Integer limitQueryRows = LIMITS.getLimitQueryRows();
	private static Integer limitQueueableJobs = LIMITS.getLimitQueueableJobs();
	private static Integer limitSoslQueries = LIMITS.getLimitSoslQueries();
	private static Boolean queueable = System.isQueueable();
	private static Boolean future = System.isFuture();
	private static Boolean scheduled = System.isScheduled();
	private static Boolean batchable = System.isBatch();
	//if limit logger is not set to debugLogs or commitLogs, nothing happens. 
	private static Boolean limitLoggerEnabled { get{ 
		return (commitLogs || debugLogs);
	}}

	// transaction number will be shared by all records of the same execution context
	private static Double transactionNumber = Math.random() * 10000000;
	private static Integer logStartOrder = 0;
	private static Integer logStopOrder = 0;

	/* Methods */

	/**
	* Stops the current log. If it is the initial log that was constructed, then the logs are committed to the database
	*/
	public void stop() {
		if(!limitLoggerEnabled) { return;}
		stopped = true;
		updateLog();

		printLimits();
		addLogToList();
		if(limitLoggerSettings.Auto_Commit_When_Initial_Is_Stopped__c) {
			commitAll();
		}
	}

	/**
	*  Saves the log: either adds to the static variable to commit later or if it is the initial log in the stack it will commit all of them.
	*/
	public void commitAll() {
		if(commitLogs && initialLog.stopped == true) {
			Savepoint sp = Database.setSavepoint();

			try {
				insert uncommittedRecords;
				if(limitLoggerSettings.Set_Wrapper_Relationships_Between_Logs__c) {
					allWorkingRecords.addAll(uncommittedRecords);
					List<Limit_Log__c> toUpdate = setParentChildRelations(allWorkingRecords);
					update toUpdate;
				}

				uncommittedRecords = new List<Limit_Log__c>();

				//establish parent child relationship
				//sort by max spread
				

				initialLog = null;
			} catch (exception e) {
				System.debug(e);
				Database.rollback(sp);
			}
		} else {
			if(!commitLogs) {
				System.debug('Did not commit logs. CommitLogs set to: ' + commitLogs);
			}
			if(initialLog != null && initialLog.stopped == false) {
				System.debug(Label.STOP_INITIAL_LOG_BEFORE_COMMIT);
			}
		}
	}

	/**
	* Starts the current log and resets the initial values to zero
	*/
	private void start() {
		if(!limitLoggerEnabled) { return;}
		this.startTime 						= System.now().getTime();
		this.initialAggregateQueries 		= LIMITS.getAggregateQueries();
		this.initialAsyncCalls 				= LIMITS.getAsyncCalls();
		this.initialCallouts 				= LIMITS.getCallouts();
		this.initialCpuTime 				= LIMITS.getCpuTime();
		this.initialDMLRows 				= LIMITS.getDMLRows();
		this.initialDMLStatements 			= LIMITS.getDMLStatements();
		this.initialEmailInvocations 		= LIMITS.getEmailInvocations();
		this.initialFutureCalls 			= LIMITS.getFutureCalls();
		this.initialHeapSize 				= LIMITS.getHeapSize();
		this.initialMobilePushApexCalls 	= LIMITS.getMobilePushApexCalls();
		this.initialQueries 				= LIMITS.getQueries();
		this.initialQueryLocatorRows 		= LIMITS.getQueryLocatorRows();
		this.initialQueryRows 				= LIMITS.getQueryRows();
		this.initialQueueableJobs 			= LIMITS.getQueueableJobs();
		this.initialSoslQueries 			= LIMITS.getSoslQueries();
		this.triggerIsExecuting				= Trigger.isExecuting;
		if(Trigger.isExecuting) {
			this.triggerSize 				= Trigger.size;
			this.triggerContext				= new Set<String>{String.valueOf(trigger.operationType)};
		}
	}

	private List<Limit_Log__c> setParentChildRelations(List<Limit_Log__c> records) {
		Map<Id, Limit_Log__c> toUpdateMap = new Map<Id, Limit_Log__c>();
		Map<Integer, List<Limit_Log__c>> limitLogBySpread = new Map<Integer, List<Limit_Log__c>>();
		for(Limit_Log__c ll: records) {
			if(ll.Id == initialLog.record.Id) { continue; }
			if(ll.Wrapper_Limit_Log__c == null) {
				ll.Wrapper_Limit_Log__c = initialLog.record.Id;
				toUpdateMap.put(ll.Id, ll);
			}
			Integer spread = (Integer)(ll.Log_Stop_Order__c - ll.Log_Start_Order__c);
			List<Limit_Log__c> spreadList = limitLogBySpread.get(spread);
			if(spreadList == null) { 
				spreadList = new List<Limit_Log__c>(); 
			}
			spreadList.add(ll);
			limitLogBySpread.put(spread, spreadList);
		}
		List<Integer> spreadKeyList = new List<Integer>(limitLogBySpread.keySet());
		spreadKeyList.sort();

		for(Integer i = spreadKeyList.size() -1; i >= 0; i--) { //loop through super sets in reverse, maximum first
			Integer superSetLogKey = spreadKeyList[i];
			List<Limit_Log__c> superSetLogs = limitLogBySpread.get(superSetLogKey);
			for(Limit_Log__c superLog: superSetLogs) {
				for(Integer subsetLogKey: spreadKeyList) { //loop through subset from smallest first
					if(superSetLogKey < subsetLogKey) { continue; }
					List<Limit_Log__c> subSetLogs = limitLogBySpread.get(subsetLogKey);
					for(Limit_Log__c subLog: subSetLogs) {
						if(superLog.Log_Start_Order__c >= subLog.Log_Start_Order__c) {
							continue;
						} 
						if(superLog.Log_Stop_Order__c <= subLog.Log_Stop_Order__c) {
							continue; //
						}
						//TODO - known issue - will update even if it doesn't need to due to the way it loops through the super / sub set
						if(subLog.Wrapper_Limit_Log__c != superLog.Id) { 
							subLog.Wrapper_Limit_Log__c = superLog.Id;
							toUpdateMap.put(subLog.Id, subLog);
						}
					}
				}
			}
		}
		return toUpdateMap.values();
	}
	/**
	*  Initializes the limit log record
	*/
	private void initializeLimitLogRecord() {
		this.record = new Limit_Log__c(
			Log_Start_Order__c 				= logStartOrder,
			Event_Name__c 					= eventName,
			Transaction__c 					= transactionNumber,
			Aggregate_Queries_Limit__c 		= limitAggregateQueries,
			Async_Calls_Limit__c			= limitAsyncCalls,
			Callouts_Limit__c				= limitCallouts,
			CPU_Time_Limit__c				= limitCpuTime,
			DML_Rows_Limit__c				= limitDMLRows,
			DML_Statements_Limit__c			= limitDMLStatements,
			Email_Invocations_Limit__c		= limitEmailInvocations,
			Future_Calls_Limit__c			= limitFutureCalls,
			Heap_Size_Limit__c				= limitHeapSize,
			Mobile_Push_Apex_Calls_Limit__c	= limitMobilePushApexCalls,
			Queries_Limit__c				= limitQueries,
			Query_Locator_Rows_Limit__c		= limitQueryLocatorRows,
			Query_Rows_Limit__c				= limitQueryRows,
			Queueable_Jobs_Limit__c			= limitQueueableJobs,
			Sosl_Queries_Limit__c			= limitSoslQueries,
			Queueable__c					= queueable,
			Future__c						= future,
			Scheduled__c					= scheduled,
			Batchable__c					= batchable
		);
	}

	/**
	*  Updates the log with the current and cumulative usage
	*/
	private void updateLog() {
		record.Aggregate_Queries_Used__c				= this.cumulativeAggregateQueries 		- this.initialAggregateQueries;
		record.Cumulative_Aggregate_Queries_Used__c		= this.cumulativeAggregateQueries;
		
		record.Async_Calls_Used__c						= this.cumulativeAsyncCalls 			- this.initialAsyncCalls;
		record.Cumulative_Async_Calls_Used__c			= this.cumulativeAsyncCalls;
		
		record.Callouts_Used__c							= this.cumulativeCallouts 				- this.initialCallouts;
		record.Cumulative_Callouts_Used__c				= this.cumulativeCallouts;
		
		record.CPU_Time_Used__c							= this.cumulativeCpuTime 				- this.initialCpuTime;
		record.Cumulative_CPU_Time_Used__c				= this.cumulativeCpuTime;
		
		record.DML_Rows_Used__c							= this.cumulativeDMLRows 				- this.initialDMLRows;
		record.Cumulative_DML_Rows_Used__c				= this.cumulativeDMLRows;
		
		record.DML_Statements_Used__c					= this.cumulativeDMLStatements 			- this.initialDMLStatements;
		record.Cumulative_DML_Statements_Used__c		= this.cumulativeDMLStatements;
		
		record.Email_Invocations_Used__c				= this.cumulativeEmailInvocations 		- this.initialEmailInvocations;
		record.Cumulative_Email_Invocations_Used__c		= this.cumulativeEmailInvocations;
		
		record.Future_Calls_Used__c						= this.cumulativeFutureCalls 			- this.initialFutureCalls;
		record.Cumulative_Future_Calls_Used__c			= this.cumulativeFutureCalls;
		
		record.Heap_Size_Used__c						= this.cumulativeHeapSize 				- this.initialHeapSize;
		record.Cumulative_Heap_Size_Used__c				= this.cumulativeHeapSize;
		
		record.Mobile_Push_Apex_Calls_Used__c			= this.cumulativeMobilePushApexCalls 	- this.initialMobilePushApexCalls;
		record.Cumulative_Mobile_Push_Apex_Calls_Used__c= this.cumulativeMobilePushApexCalls;
		
		record.Queries_Used__c							= this.cumulativeQueries 				- this.initialQueries;
		record.Cumulative_Queries_Used__c				= this.cumulativeQueries;
		
		record.Query_Locator_Rows_Used__c				= this.cumulativeQueryLocatorRows 		- this.initialQueryLocatorRows;
		record.Cumulative_Query_Locator_Rows_Used__c	= this.cumulativeQueryLocatorRows;
		
		record.Query_Rows_Used__c 						= this.cumulativeQueryRows 				- this.initialQueryRows;
		record.Cumulative_Query_Rows_Used__c 			= this.cumulativeQueryRows;
		
		record.Queueable_Jobs_Used__c					= this.cumulativeQueueableJobs 			- this.initialQueueableJobs;
		record.Cumulative_Queueable_Jobs_Used__c		= this.cumulativeQueueableJobs;
		
		record.Sosl_Queries_Used__c						= this.cumulativeSoslQueries 			- this.initialSoslQueries;
		record.Cumulative_Sosl_Queries_Used__c			= this.cumulativeSoslQueries;
		
		record.Records_Processed__c 					= sObjectList != null ? sObjectList.size() : null;
		record.Time__c 									= System.now().getTime() - startTime;

		record.Trigger_Is_Executing__c 					= triggerIsExecuting;
		if(Trigger.isExecuting) {
			triggerContext.add(String.valueOf(Trigger.operationType));
			record.Trigger_Size__c						= triggerSize;
			for(String context: triggerContext) {
				record.Trigger_Contexts__c = context + ';';	
			}
		}

	}
	/**
	*  Prints the record fields in the debug log
	*/
	private void printLimits() {
		if(debugLogs) {
			for(String fieldName: this.record.getPopulatedFieldsAsMap().keySet()) {
				if(!fieldName.contains('Used__c')) { continue; }
				System.debug(this.eventName + ': ' + fieldName.replace('__c', '').replace('_', ' ') + ':' + this.record.get(fieldName));
			}
		}
	}
	/**
	*  Adds log to the list for saving later
	*/
	private void addLogToList() {
		if(commitLogs) {
			uncommittedRecords.add(record);
		}
	}
}